                # Minehook #
# Discord Webhook Integration Plugin for Minecraft #
            # Plugin by KadotCom #

discordWebhook: "" # Discord Webhook URL, see tutorial on wiki on how to make a webhook:

serverName: "Minehook" # Server name, will appear at footer of messages.

log: # Settings for logging
  server: # Server logging events
    command: true # Logs when a command is run by server
    serverStart: true # Logs when the server goes online
    serverShutdown: true # Logs when the server goes offline
  player: # Player logging events
    playerJoin: true # Logs when a player joins
    playerLeave: true # Logs when a player leaves
    playerChat: true # Logs when a player sends a message
    playerDeath: true # Logs when a player dies
    playerKick: true # Logs when a player gets kicked
    command: true # Logs when a command is run by player


